logging:
  level:
    root: info

postgres:
  username: postgres
  password: postgres
  schema: video
  url: localhost:${postgres.port}

amqp:
  host: localhost
  port: 5672
  username: adm_video
  password: 123456

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

keycloak:
  realm: test
  host: http://test:8443