apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerenciador-nginx-controller
  namespace: gerenciador-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerenciador-nginx
  template:
    metadata:
      labels:
        app: gerenciador-nginx
    spec:
      containers:
        - name: gerenciador-nginx-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1
          args:
            - /nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
            - --annotations-prefix=nginx.ingress.kubernetes.io
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443